type: fit
environment:
  hex:
    k: 5
actor:
  hidden_sizes: [128, 256, 256, 128, 64]
  learning_rate: 8e-3
  decay: 1e-2
  optimizer: 'adam'
  activation: 'leaky_relu'
fit:
  n_games: 200
  n_search_games: 500
  batch_size: 100
  buffer_size: 1000
  epochs: 5
  checkpoint_iter: 5
  visualize: False
